# -*- coding: utf-8 -*-
"""diary_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gnCLDht5uEOvBDrryyq31eTUNw66vfW
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/ikoma/diary_app')

from google.colab import files
files.view("diary_app.py")

!streamlit run diary_app.py & sleep 3 && npx localtunnel --port 8501

